const RESPONSE_CODE = {
  DEFAULT: "SUCCESS",
  LOGIN: "LOGIN",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  ERROR: "ERROR",
  ALERTS: "ALERTS",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  NOT_VERIFIED: "NOT_VERIFIED",
};

module.exports = {
  RESPONSE_CODE,
};
